
# Project name
name: 'bitcoin_cash'
version: '1.0.0'

# Project profile
profile: 'bitcoin_cash'

# These configurations specify where dbt should look for different types of files.
model-paths: ["bitcoin_cash/models"]
test-paths: ["bitcoin_cash/tests"]
macro-paths: ["bitcoin_cash/macros"]


 # Directories to be removed by dbt clean
clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
models:
  bitcoin_cash:
    # Config indicated by + and applies to all files under models/bitcoin_cash/
    staging:
      +materialized: table
      +schema: "staging"

    mart:
      +materialized: table
      +schema: "mart"
